workspace:
  base: /flask-todo
  path: src/github.com/mrmoneyc/flask-todo

pipeline:
  frontend:
    image: node:9
    commands:
      - cd frontend
      - yarn
      - yarn run build
  build-publish-image:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: mrmoneyc/flask-todo
    tag:
      - build-from-ci
    dockerfile: ./Dockerfile
    context: .
