---
- include_vars: "{{ ansible_os_family }}.yml"

- name: Add zypper repository
  zypper_repository:
    name: server-database
    repo: '{{ mariadb_repository[item] }}'
    auto_import_keys: yes
    state: present
  with_items: '{{ ansible_distribution_version }}'
  when: mariadb_install_from_upstream

- name: Install MariaDB server and client package
  zypper:
    name: '{{ item }}'
    state: present
  with_items:
    - mariadb
    - mariadb-client
    - libmysqlclient-devel

- name: Install MySQL-python package
  zypper:
    name: python-MySQL-python
    state: present
  when: not mariadb_mysql_python_from_pip

- name: Install PIP
  zypper:
    name: '{{ item }}'
    state: present
  with_items:
    - python
    - python-devel
    - python-pip
  when: mariadb_mysql_python_from_pip

- name: Install MySQL-python from PIP
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - mysqlclient
    - mysql-python
  when: mariadb_mysql_python_from_pip
  ignore_errors: yes
