---
- import_playbook: setup-sysctl.yml

- name: Initial node
  hosts: '{{ host }}'
  remote_user: '{{ sysop_user }}'
  become: true
  tasks:
    - name: Add apps group
      group:
        name: '{{ ap_user }}'
        state: present
    - name: Add apps user and setup groups
      user:
        name: '{{ ap_user }}'
        group: '{{ ap_user }}'
        append: yes
        shell: /bin/bash
    - name: Install essential packages
      zypper:
        name: '{{ item }}'
        state: present
      with_items:
        - cron
        - git
        - htop
        - mutt
        - mosh
        - sshpass
        - tmux
        - vim
      when: ansible_os_family == 'Suse'
    - name: Install Python, PIP, Node.js
      zypper:
        name: '{{ item }}'
        state: present
      with_items:
        - python
        - python-pip
        - python-devel
        - python3
        - python3-pip
        - python3-devel
        - python3-virtualenv
        - nodejs6
        - npm6
      when: ansible_os_family == 'Suse'
    - name: Install Basic Development Tools
      zypper:
        name: '{{ item }}'
        state: present
        type: pattern
      with_items:
        - devel_basis
      when: ansible_os_family == 'Suse'
