---
- name: Initial sysctl
  hosts: '{{ host }}'
  remote_user: '{{ sysop_user }}'
  become: true
  vars:
    sysctl_config_casehsu: /etc/sysctl.d/99-casehsu.conf
  tasks:
    - name: Setup file.max
      sysctl:
        name: fs.file-max
        value: 524288
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
    - name: Setup net.core.somaxconn
      sysctl:
        name: net.core.somaxconn
        value: 65535
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
    - name: Setup net.core.rmem_default
      sysctl:
        name: net.core.rmem_default
        value: 8388608
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
    - name: Setup net.core.wmem_default
      sysctl:
        name: net.core.wmem_default
        value: 8388608
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
    - name: Setup net.core.rmem_max
      sysctl:
        name: net.core.rmem_max
        value: 16777216
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
    - name: Setup net.core.wmem_max
      sysctl:
        name: net.core.wmem_max
        value: 16777216
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
    - name: Setup net.core.netdev_max_backlog
      sysctl:
        name: net.core.netdev_max_backlog
        value: 250000
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
    - name: Load kernel module
      modprobe:
        name: ip_conntrack
        state: present
    - name: Setup net.nf_conntrack_max
      sysctl:
        name: net.nf_conntrack_max
        value: 131072
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
      ignore_errors: yes
    - name: Setup net.netfilter.nf_conntrack_tcp_timeout_established
      sysctl:
        name: net.netfilter.nf_conntrack_tcp_timeout_established
        value: 1200
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
      ignore_errors: yes
    - name: Setup net.ipv4.tcp_max_syn_backlog
      sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: 8192
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
    - name: Setup net.ipv4.tcp_keepalive_time
      sysctl:
        name: net.ipv4.tcp_keepalive_time
        value: 300
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
    - name: Setup net.ipv4.tcp_tw_reuse
      sysctl:
        name: net.ipv4.tcp_tw_reuse
        value: 1
        sysctl_set: yes
        sysctl_file: '{{ sysctl_config_casehsu }}'
        state: present
